// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vydqeonomxkrbvdoywxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZHFlb25vbXhrcmJ2ZG95d3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDk1NzAsImV4cCI6MjA3MjAyNTU3MH0.p1Xex6T_z5iCRMTl0XbxuXmQxQLezTtIsXuBpGRaloM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});